
# general rcodes
000 = "Success."
001 = "Unknown failure."
002 = "Can't find root directory."
003 = "Can't find rcode in table."
004 = "Test termination."

# preproc
100 = "Source file doesn't exist."
