[package]
name = "common"
version = "0.1.0"
authors = ["Damian Grüner <grunerdamian@gmail.com>"]
edition = "2018"

[dependencies]
logos = "0.12.0"
lalrpop-util = "0.19"
serde_json = "1.0.64"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
lalrpop = "0.19"
